version: "3.8"

services:
  pipeline:
    build: .
    container_name: data_pipeline
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - pipeline_network
    tty: true
    stdin_open: true

  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: weather_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pipeline_network:
    driver: bridge

volumes:
  postgres_data:
